### ISSUE TITLE
HTML and CSS beautify functions are not included

### ISSUE THREAD

**Issue by gucu112** [sedouard/grunt-js-beautify#2]
Hi @sedouard !

I have looked into your code today and I have a proposition to use also HTML and CSS beautify functions **depends on file extension**. If I manage some time yesterday I will try to make a pull request with changes releated to the improvement.

**Comment by sedouard** [comment]
Hey there! I'm not sure if I follow... JSBeautifier only formats javascript. Can you explain a bit more?

**Comment by gucu112** [comment]
That's not exactly true. As far as I dig into documentation [here](https://github.com/beautify-web/js-beautify#css--html), you can see there's such an option :)
Your code only needs to determine extension of file (it can be easily done with node **path** module) and then use particular beautifying function.

**Comment by sedouard** [comment]
😆 Well will you look at that! Didn't realize JSBeautifier did that as well. Nice 👌🏽

Actually now that I think about this I will probably deprecate this package as [`grunt-jsbeautifier`](https://npmjs.org/grunt-jsbeautifier) seems like the popular choice. I may have written this package before I knew it existed? Or maybe before hand. I'd recommend contributing to that module and not this one.
